version: "3.9"

services:
  express:
    build: .
    network_mode: "host"
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./logs:/logs
      - ./src/db:/src/db
    restart: always
